#!/bin/sh
go install github.com/OWASP/Amass/v3/...@latest
go install github.com/tomnomnom/assetfinder@latest
go install github.com/projectdiscovery/cf-check/cmd/cf-check@latest
go install github.com/dnstake/dnstake@latest
go install github.com/getzola/getJS@latest
go install github.com/jaeles-project/gospider@latest
go install github.com/sensepost/gowitness@latest
go install github.com/KathanP19/Gxss@latest
go install github.com/hakluke/hakoriginfinder@latest
go install github.com/hakluke/hakrevdns@latest
go install github.com/projectdiscovery/httpx/cmd/httpx@latest
go install github.com/ropnop/kerbrute@latest
go install github.com/projectdiscovery/mapcidr/cmd/mapcidr@latest
go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
go install github.com/tomnomnom/qsreplace@latest
go install github.com/abhnv/shosubgo@latest
go install github.com/lc/subjs@latest
go install github.com/tomnomnom/waybackurls@latest
go install github.com/tomnomnom/anew@latest
go install github.com/projectdiscovery/cdncheck/cmd/cdncheck@latest
go install github.com/hahwul/dalfox@latest
go install github.com/lc/gau@latest
go install github.com/tomnomnom/gf@latest
go install github.com/Josue87/gotator@latest
go install github.com/tomnomnom/gron@latest
go install github.com/hakluke/hakip2host@latest
go install github.com/hakluke/hakrawler@latest
go install github.com/tomnomnom/httprobe@latest
go install github.com/projectdiscovery/katana/cmd/katana@latest
go install github.com/Emoe/kxss@latest
go install github.com/tomnomnom/meg@latest
go install github.com/projectdiscovery/page-fetch/cmd/page-fetch@latest
go install github.com/anonx10/s3scanner@latest
go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
go install github.com/tomnomnom/unfurl@latest
go install github.com/Hackmanit/Web-Cache-Vulnerability-Scanner@latest
go install github.com/BishopFox/jsluice/cmd/jsluice@latest
